name: Build - Current

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install-dependancies
      run : sudo apt install nasm xorriso gcc grub-pc grub-pc-bin mtools
    
    - name: build
      run : make build-x86_64
