name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install-dependancies
      run : apt install nasm xorriso gcc
    
    - name: build
      run : make build-x86_64
